import Head from 'next/head'

import { Container, Heading, Stack } from '@chakra-ui/react'

import FilterSection from '~/components/FilterSection'
import TableSection from '~/components/TableSection'

const Home = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <Container maxW="6xl" my={12}>
        <Stack spacing={4}>
          <Heading as="h1" size="lg" noOfLines={1}>
            Meetings
          </Heading>
          <FilterSection />
          <TableSection />
        </Stack>
      </Container>
    </main>
  </>
)

export default Home
